### ISSUE TITLE
Extensión también elimina los artículos 'usados'

### ISSUE THREAD

**Issue by Keno-GH** [ivanMSC/LibreMercadoPorFin#1]
Al hacer click, los artículos 'usados' también desaparecen.

**Comment by ivanMSC** [comment]
Hola! Gracias. No había probado ese caso.

Sé por qué pasa eso. Veré como lo arreglo a la noche.

**Comment by ivanMSC** [comment]
Ya lo arreglé. Era fácil.

Gracias.

**Comment by Keno-GH** [comment]
Muchas gracias!
