### ISSUE TITLE
Gracias por tanto

### ISSUE THREAD

**Issue by rodrigopv** [ivanMSC/LibreMercadoPorFin#2]
Probé este XPath para llegar directo al li, solo por la ciencia 😂

`//*[@id="root-app"]/div/div/section/ol/li[./div/div/div/div/div//span[contains(@class, 'ui-search-item__details') and contains(text(), 'Internacional')] and contains(@class, 'ui-search-layout__item')]`

En Chrome logré ejecutarlo en la consola de manera 1-liner así:

`$x('//*[@id="root-app"]/div/div/section/ol/li[./div/div/div/div/div//span[contains(@class, "ui-search-item__details") and contains(text(), "Internacional")] and contains(@class, "ui-search-layout__item")]').forEach(e => e.parentNode.removeChild(e));`

Llevaba como 1 día vitrineando mercadolibre cuando caché el tema de internacional y simplemente pasaba de largo, pero definitivamente tuviste un gran acierto con esta idea!

**Comment by rodrigopv** [comment]
Le dí un poco más de tiempo a implementar esto y queda así:

```
function myMain () {
    var internationalLinks = document.evaluate (
		"//*[@id=\"root-app\"]/div/div/section/ol/li[./div/div/div/div/div//span[contains(@class, \"ui-search-item__details\") and contains(text(), \"Internacional\")] and contains(@class, \"ui-search-layout__item\")]",
		document,
		null,
		XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
		null
    );
	var numLinks = internationalLinks.snapshotLength;

	for (var idx = 0;  idx < numLinks;  ++idx) {
		var item = internationalLinks.snapshotItem (idx);
		item.parentNode.removeChild(item);
	}
}
```

Le di hartas vueltas al asunto de encontrar el evento exacto para aplicar la función, sin embargo el único evento perfecto era uno custom de LastPass 😔👌 (lprequestend).

Obviamente no podemos depender de tener LastPass instalado para que esto funcione. Quizás el camino sea insertar un botón para remover internacional opcionalmente (?)

**Comment by ivanMSC** [comment]
La versión actual de la extension corre dos veces por segundo buscando elementos internacionales (colaboración de @jkcgs)

**Comment by rodrigopv** [comment]
creo que LastPass intercerpeta XmlHttpRequest para lograr los custom events lprequeststart y lprequestend.

Hubiera sido ideal no tener que depender de un timer o ejecutar más veces de lo necesario pero así es la vida 😔👌
