### ISSUE TITLE
Propuesta de mejora

### ISSUE THREAD

**Issue by ivanMSC** [ivanMSC/LibreMercadoPorFin#5]
Primero que cualquier cosa, ~~la extensión ha quedado obsoleta.~~ Mercadolibre ofrece filtrar en forma nativa aquellas tiendas internacionales (Me gusta pensar que este trabajo tuvo algo que ver en ello. Probablemente no). 

Para no quedar obsoletos, propongo una mejora a la extensión. Existen resultados que no son facilmente filtrables, ya que no se distinguen directamente desde la página de resultados de búsqueda. Me refiero a aquellos importadores que no son "internacionales" pero que igual traen mierda de China. La forma de saber quienes son es entrando a la publicación, encontrando el texto naranjo que dice "Disponible X días después de tu compra".

Para implementar esto, se deberá modificar la extensión para que haga fetch de cada resultado luego del primer filtrado de "internacional".  En cada fetch se debería verificar si está el elemento de letras naranjas que dice "Disponible X días después de tu compra"

Esto tiene un daño colateral. Podría llegar a borrar resultados que sean honestos. Por ejemplo, algún artesano que trabaje a pedido y que disponga que su trabajo estará listo 10 días luego de la compra. Imagino que podría colocar un botón en algún lado para activar o desactivar el filtro y aminorar el daño colateral.

![image](https://user-images.githubusercontent.com/35350256/120120470-7b58a300-c16b-11eb-8ff6-3a14be353194.png)

**Comment by ivanMSC** [comment]
Además, cómo cresta un hámster parlante va a costar más de 40 lucas?

**Comment by ivanMSC** [comment]
En realidad no está obsoleta. La extensión permite filtrar por defecto los elementos molestos. No lo había pensado así. Así que qué bueno.

**Comment by Argyos** [comment]
Sería algo como...

Entrar por cada resultado obtener el html content, leer el div y ocultar esa posc o no según un threshold ?

Aún le veo potencial para aquellos vendedores que igual hacen pasar un item como nacional cuando no es

**Comment by ivanMSC** [comment]
cors me cagó.

**Comment by ivanMSC** [comment]
Se me habia olvidado esto. Al final lo implementé en la v1.2.2
