### ISSUE TITLE
Mercadolibre cambio y ahora se muestran

### ISSUE THREAD

**Issue by Argyos** [ivanMSC/LibreMercadoPorFin#6]
Adjunto una imagen como muestra:
![image](https://user-images.githubusercontent.com/24982055/120400759-88f95e80-c30c-11eb-9ba1-fe12d0fe0141.png)

particularmente uso el script con TamperMonkey

**Comment by ivanMSC** [comment]
@New-Key Curioso. Ayer vi que mercado libre implementó el filtro de compras internacionales de forma nativa. Así que en teoría nla extensión ya no sería necesaria.

De todas formas, veré la posibilidad de actualizar la extensión ya que igual es útil pues filtra por defecto.

**Comment by Argyos** [comment]
Ciertamente ya hay un filtro encargado para ese tema, sería genial ya dejarlo por defecto. gracias!

**Comment by ivanMSC** [comment]
@New-Key Estaría arreglado. Por favor, si puedes reinstalar la extensión y comprobar si funciona sin problemas.
